default: 00 01 02 03 04 05

OPTS ?= --logging=DEBUG

00:
	pycomment ${OPTS} --inplace 00*.py
01:
	pycomment ${OPTS} --inplace 01*.py
02:
	pycomment ${OPTS} --inplace 02*.py
03:
	pycomment ${OPTS} --inplace 03*.py
04:
	pycomment ${OPTS} --inplace 04*.py
05:
	pycomment ${OPTS} --inplace 05*/main.py
